2016-12-24 07:57:22,094 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
